apiVersion: v1
kind: Service
metadata:
  name: {{ SERVICE_NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    tier: backend
spec:
  selector:
    app: redis
    tier: backend
  ports:
    - protocol: TCP
      port: {{ SERVICE_PORT }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: redisdb
        image: redis:6.2.4
        ports:
        - containerPort: 6379
